spring:
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
  redis:
      database: 9
      host: 39.105.169.182
      port: 6379
      password:
      # 连接超时时间（毫秒）
      timeout: 900000
      jedis:
        pool:
          max-wait: -1
          min-idle: 1
          max-active: 100
          max-idle: 50


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.169.182:3306/test?useUnicode=true&characterEncoding=utf8
    #url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    tomcat:
      min-idle: 20
      max-active: 200
      max-wait: 30000
  jackson:
    serialization:
      indent_output: true  #让控制器输出json字符串形式美感