logging:
  file: F:\\zhihui\\github\\miaosha-\\springboot_1\\src\\main\\resources\\log.log
  level:
    cn.bdqn: debug
    org:
     springframework:
      security: debug
spring:
  profiles:
    active: dev
logging.f